# Testeos de todas las rutas:

### Login de usuario (merchant)

POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "banana@gmail.com",
    "password": "Prueba1234!"
    
}

### Login de usuario (admin)

POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "Admin1234!!"
    
}

### Login de usuario (user)

POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "Aladin@gmail.com",
    "password": "Aladin1234!"
    
}

### registro de usuario (el admin)

POST http://localhost:3000/api/auth/users HTTP/1.1
Content-Type: application/json

{
    "name": "Admin",
    "age": "23",
    "email": "admin@gmail.com",
    "password": "Admin1234!!",
    "city": "Null",
    "accepts_offers": false
  
}

### registro de usuario

POST http://localhost:3000/api/auth/users HTTP/1.1
Content-Type: application/json

{
    "name": "Aladin",
    "age": "23",
    "email": "Aladin@gmail.com",
    "password": "Aladin1234!",
    "city": "Malaga",
    "accepts_offers": true,
    "interests": ["bebida", "futbol"]
  
}

### Registro de Merchant(company y user con rol merchant) hecho desde un admin

POST http://localhost:3000/api/auth/merchant HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InVzZXIiLCJpYXQiOjE2ODM3Mzc2MjEsImV4cCI6MTY4Mzc1MjAyMX0.X7T-cIOCMEozgNhUwZnBYjBaYhO4YoX9ZJgEWlpVhHg

{
    "username": "banana_company",
    "password": "Prueba1234!",
    "city": "Madrid",
    "age": "32",

    "company_name": "Banana",
    "phone": "618111456",
    "address": "calle la q sea 32",
    "cif": "B12459786",
    "email": "banana@gmail.com"
}

### Registro de otro Merchant(company y user con rol merchant) hecho desde un admin

POST http://localhost:3000/api/auth/merchant HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InVzZXIiLCJpYXQiOjE2ODM3Mzc2MjEsImV4cCI6MTY4Mzc1MjAyMX0.X7T-cIOCMEozgNhUwZnBYjBaYhO4YoX9ZJgEWlpVhHg

{
    "username": "apple_company",
    "password": "Prueba1234!",
    "city": "Malaga",
    "age": "32",

    "company_name": "Apple",
    "phone": "618111456",
    "address": "otra calle random 32",
    "cif": "V21447818",
    "email": "apple@gmail.com"
}

### Update de usuario

PUT http://localhost:3000/api/users/id/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InVzZXIiLCJpYXQiOjE2ODMzMDk5NDUsImV4cCI6MTY4MzMyNDM0NX0.zIIJlwv8iOG3LPlq7b-MGgLohtgVulOIsDeA1h-okfw

{
    "name": "ASD",
    "age": "12",
    "address": "dasfafsd",
    "cif": "G12345678",
    "city": "Malaga"
}

### borrar un usuario(ya sea merchant o user, los admin solo se peuden borrar a mano)

DELETE http://localhost:3000/api/users/id/85 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ODUsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjgzODI2OTUzLCJleHAiOjE2ODM4NDEzNTN9.0MlhWCrPZ0n93M5Tsrff_cZwb0CCHoojCx0cNuvXMhg

### get user desde un admin 

GET http://localhost:3000/api/users/id/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InVzZXIiLCJpYXQiOjE2ODMzMDk5NDUsImV4cCI6MTY4MzMyNDM0NX0.zIIJlwv8iOG3LPlq7b-MGgLohtgVulOIsDeA1h-okfw

### get merchants desde un admin 

GET http://localhost:3000/api/users/merchants HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InVzZXIiLCJpYXQiOjE2ODMzMDk5NDUsImV4cCI6MTY4MzMyNDM0NX0.zIIJlwv8iOG3LPlq7b-MGgLohtgVulOIsDeA1h-okfw

### Registro de una Webpage desde un merchant

POST http://localhost:3000/api/webpages HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mywicm9sZSI6Im1lcmNoYW50IiwiaWF0IjoxNjgzODI4ODg2LCJleHAiOjE2ODM4NDMyODZ9.ogCGh1APUeP8mm6Ih9F-k0jT561-Z82YbxHs5-2KTOU

{
    "city": "Malaga",
    "interests": ["comida", "bebida"],
    "title": "100 Montaditos",
    "summary": "a comer bocatas"
}

### Update de la Webpage

PUT http://localhost:3000/api/webpages/id/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mywicm9sZSI6Im1lcmNoYW50IiwiaWF0IjoxNjgzNzM3NzAzLCJleHAiOjE2ODM3NTIxMDN9.ZHsgn1uiPSGlYWr_URR4XEteLF07ueT7tEJwrhaNEao

{
    "city": "Malaga",
    "title": "TGB",
    "summary": "a comer amburgesa"
}

### Crear una review

PATCH http://localhost:3000/api/webpages/id/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ODUsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjgzODIzNDM5LCJleHAiOjE2ODM4Mzc4Mzl9.MMrXR5nVaI-yYOWpDmWr1ssUAPdtkI0bEDdTfmVWShA

{
    "score": 5
}

### Get todas las webpages

GET http://localhost:3000/api/webpages/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Niwicm9sZSI6InVzZXIiLCJpYXQiOjE2ODM3MzkwMTYsImV4cCI6MTY4Mzc1MzQxNn0.V2hn-1B_Z2p5HMvvK91qqz_B91Xh1n2ChaSA-t7cL5M


### Get una webpage

GET http://localhost:3000/api/webpages/id/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Niwicm9sZSI6InVzZXIiLCJpYXQiOjE2ODM3MzkwMTYsImV4cCI6MTY4Mzc1MzQxNn0.V2hn-1B_Z2p5HMvvK91qqz_B91Xh1n2ChaSA-t7cL5M

### Get una webpage por ciudad y actividad

GET http://localhost:3000/api/webpages/search/Malaga HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Niwicm9sZSI6InVzZXIiLCJpYXQiOjE2ODM3MzkwMTYsImV4cCI6MTY4Mzc1MzQxNn0.V2hn-1B_Z2p5HMvvK91qqz_B91Xh1n2ChaSA-t7cL5M

### Get una webpage por ciudad y actividad

GET http://localhost:3000/api/webpages/search/Malaga/bebida HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Niwicm9sZSI6InVzZXIiLCJpYXQiOjE2ODM3MzkwMTYsImV4cCI6MTY4Mzc1MzQxNn0.V2hn-1B_Z2p5HMvvK91qqz_B91Xh1n2ChaSA-t7cL5M

