# Testeos de todas las rutas:

### Login de usuario (merchant)

POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "banana@gmail.com",
    "password": "Prueba1234!"
    
}

### Login de usuario (admin)

POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "Admin1234!!"
    
}

### registro de usuario

POST http://localhost:3000/api/auth/users HTTP/1.1
Content-Type: application/json

{
    "name": "Admin",
    "age": "23",
    "email": "admin@gmail.com",
    "password": "Admin1234!!",
    "city": "Null",
    "accepts_offers": false
  
}

### Registro de Merchant(company y user con rol merchant) hecho desde un admin

POST http://localhost:3000/api/auth/merchant HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InVzZXIiLCJpYXQiOjE2ODM1NTEyMjYsImV4cCI6MTY4MzU2NTYyNn0.rKGj57RKiuplXcV-xSg8QO7cxTtPd5VZ67zZnVKJDig

{
    "username": "banana_company",
    "password": "Prueba1234!",
    "city": "Madrid",
    "age": "32",

    "company_name": "Banana",
    "phone": "618111456",
    "address": "calle la q sea 32",
    "cif": "B12459786",
    "email": "banana@gmail.com"
}

### Update de usuario

PUT http://localhost:3000/api/users/id/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InVzZXIiLCJpYXQiOjE2ODMzMDk5NDUsImV4cCI6MTY4MzMyNDM0NX0.zIIJlwv8iOG3LPlq7b-MGgLohtgVulOIsDeA1h-okfw

{
    "name": "ASD",
    "age": "12",
    "address": "dasfafsd",
    "cif": "G12345678",
    "city": "Malaga"
}

### borrar un usuario(ya sea merchant o user, los admin solo se peuden borrar a mano)

DELETE http://localhost:3000/api/users/id/5 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InVzZXIiLCJpYXQiOjE2ODMzMDk5NDUsImV4cCI6MTY4MzMyNDM0NX0.zIIJlwv8iOG3LPlq7b-MGgLohtgVulOIsDeA1h-okfw

### get user desde un admin 

GET http://localhost:3000/api/users/id/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InVzZXIiLCJpYXQiOjE2ODMzMDk5NDUsImV4cCI6MTY4MzMyNDM0NX0.zIIJlwv8iOG3LPlq7b-MGgLohtgVulOIsDeA1h-okfw

### get merchants desde un admin 

GET http://localhost:3000/api/users/merchants HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InVzZXIiLCJpYXQiOjE2ODMzMDk5NDUsImV4cCI6MTY4MzMyNDM0NX0.zIIJlwv8iOG3LPlq7b-MGgLohtgVulOIsDeA1h-okfw

### Registro de una Webpage desde un merchant

POST http://localhost:3000/api/webpages HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Nywicm9sZSI6Im1lcmNoYW50IiwiaWF0IjoxNjgzNTU0NzIyLCJleHAiOjE2ODM1NjkxMjJ9.049HKgZCHA_akK8XGVPR-MgYZ4FuPS_0xd12btYS7v4

{
    "city": "Malaga",
    "interests": ["comida", "bebida"],
    "title": "100 Montaditos",
    "summary": "a comer bocatas"
}

### Update de la Webpage

PUT http://localhost:3000/api/webpages/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwicm9sZSI6Im1lcmNoYW50IiwiaWF0IjoxNjgzNTUyNDkxLCJleHAiOjE2ODM1NjY4OTF9.vsKjsyE7ArCigWBnG-bNb2JJViYBD-xO2Op1fl50N-E

{
    "city": "Albacete",
    "title": "TGB",
    "summary": "a comer amburgesa"
}