# Testeos de todas las rutas:

### Login de usuario (admin)

POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "Admin1234!!"
    
}

### registro de usuario

POST http://localhost:3000/api/auth/users HTTP/1.1
Content-Type: application/json

{
    "name": "Admin",
    "age": "23",
    "email": "admin@gmail.com",
    "password": "Admin1234!!",
    "city": "Null",
    "accepts_offers": false
  
}

### Registro de Merchant(store y user con rol merchant)

POST http://localhost:3000/api/auth/merchants HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciIsImlhdCI6MTY4MzE0MjE2NCwiZXhwIjoxNjgzMTU2NTY0fQ.oJoKJmwwHv9gYAjwffbB3NlQr9srh7tpRsCM1DxO5mM

{
    "store_name": "Banana",
    "username": "banana_store",
    "email": "banana@gmail.com",
    "phone": "618111456",
    "address": "calle la q sea 32",
    "cif": "B12459786",
    "password": "Prueba1234!",
    "city": "Madrid"
  
}

### Update del Merchant(Solo desde admin)

PUT http://localhost:3000/api/auth/merchants/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2ODMxNDI2MTksImV4cCI6MTY4MzE1NzAxOX0.PNYRO57PwJ0htQJT9AH3O38mjVQvNIHRF4a59MU04wc

{
    "name": "Bananeros",
    "phone": "6199999999",
    "address": "dasfafsd",
    "cif": "G12345678",
    "city": "Malaga",
    "title": "A come Platano",
    "summary": "resumen"
}

###
